---
apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  labels:
    svc: vpro-app-svc
spec:
  type: ClusterIP
  selector:
      pod: vproapp-pod
  ports:
    - port: 8080
      targetPort: vproapp-port
      protocol: TCP
