---
apiVersion: v1
kind: Service
metadata:
  name: vprodb
  labels:
    svc: vprodb-svc
spec:
  type: ClusterIP
  selector:
    pod: vprodb-pod
  ports:
    - port: 3306
      targetPort: vprodb-port
      protocol: TCP

