---
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
  labels:
    svc: vpromc-svc
spec:
  type: ClusterIP
  selector:
    pod: vpromc-pod
  ports:
    - port: 11211
      targetPort: vpromc-port
      protocol: TCP

