---
apiVersion: v1
kind: Service
metadata:
  name: vpromq01
  labels:
    svc: vprormq-svc
spec:
  type: ClusterIP
  selector:
    pod: vprormq-pod
  ports:
    - port: 5672
      targetPort: vprormq-port
      protocol: TCP

